# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: olm
description: Dart bindings for Olm, an implementation of the olm and megolm cryptographic ratchets
version: 2.0.4
homepage: https://github.com/famedly/dart-olm
repository: https://github.com/famedly/dart-olm.git
issues: https://github.com/famedly/dart-olm/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  js: ^0.6.4
  ffi: ^2.0.0

dev_dependencies:
  coverage: ^1.0.1
  import_sorter: ^4.6.0
  test: ^1.21.4
  benchmark_harness: any
