// Mocks generated by Mockito 5.4.4 from annotations
// in fluffychat/test/pages/new_group/new_group_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i5;

import 'package:fluffychat/pages/new_group/new_group.dart' as _i3;
import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextEditingController_0 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNewGroup_1 extends _i1.SmartFake implements _i3.NewGroup {
  _FakeNewGroup_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeBuildContext_2 extends _i1.SmartFake implements _i2.BuildContext {
  _FakeBuildContext_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_3 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_4 extends _i1.SmartFake
    implements _i2.DiagnosticsNode {
  _FakeDiagnosticsNode_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({
    _i4.TextTreeConfiguration? parentConfiguration,
    _i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info,
  }) =>
      super.toString();
}

/// A class which mocks [NewGroupController].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewGroupController extends _i1.Mock
    implements _i3.NewGroupController {
  @override
  _i2.TextEditingController get controller => (super.noSuchMethod(
        Invocation.getter(#controller),
        returnValue: _FakeTextEditingController_0(
          this,
          Invocation.getter(#controller),
        ),
        returnValueForMissingStub: _FakeTextEditingController_0(
          this,
          Invocation.getter(#controller),
        ),
      ) as _i2.TextEditingController);

  @override
  set controller(_i2.TextEditingController? _controller) => super.noSuchMethod(
        Invocation.setter(
          #controller,
          _controller,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get publicGroup => (super.noSuchMethod(
        Invocation.getter(#publicGroup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set publicGroup(bool? _publicGroup) => super.noSuchMethod(
        Invocation.setter(
          #publicGroup,
          _publicGroup,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isCaseReference => (super.noSuchMethod(
        Invocation.getter(#isCaseReference),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isCaseReference(bool? _isCaseReference) => super.noSuchMethod(
        Invocation.setter(
          #isCaseReference,
          _isCaseReference,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get enableEncryption => (super.noSuchMethod(
        Invocation.getter(#enableEncryption),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set enableEncryption(bool? _enableEncryption) => super.noSuchMethod(
        Invocation.setter(
          #enableEncryption,
          _enableEncryption,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.NewGroup get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeNewGroup_1(
          this,
          Invocation.getter(#widget),
        ),
        returnValueForMissingStub: _FakeNewGroup_1(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i3.NewGroup);

  @override
  _i2.BuildContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeBuildContext_2(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeBuildContext_2(
          this,
          Invocation.getter(#context),
        ),
      ) as _i2.BuildContext);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setCaseReference(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setCaseReference,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPublicGroup(bool? b) => super.noSuchMethod(
        Invocation.method(
          #setPublicGroup,
          [b],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEnableEncryption(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setEnableEncryption,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void submitAction([dynamic _]) => super.noSuchMethod(
        Invocation.method(
          #submitAction,
          [_],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Widget build(_i2.BuildContext? context) => (super.noSuchMethod(
        Invocation.method(
          #build,
          [context],
        ),
        returnValue: _FakeWidget_3(
          this,
          Invocation.method(
            #build,
            [context],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_3(
          this,
          Invocation.method(
            #build,
            [context],
          ),
        ),
      ) as _i2.Widget);

  @override
  void initState() => super.noSuchMethod(
        Invocation.method(
          #initState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didUpdateWidget(_i3.NewGroup? oldWidget) => super.noSuchMethod(
        Invocation.method(
          #didUpdateWidget,
          [oldWidget],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reassemble() => super.noSuchMethod(
        Invocation.method(
          #reassemble,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setState(_i5.VoidCallback? fn) => super.noSuchMethod(
        Invocation.method(
          #setState,
          [fn],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deactivate() => super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void activate() => super.noSuchMethod(
        Invocation.method(
          #activate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeDependencies() => super.noSuchMethod(
        Invocation.method(
          #didChangeDependencies,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugFillProperties(_i4.DiagnosticPropertiesBuilder? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #debugFillProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();

  @override
  String toStringShort() => (super.noSuchMethod(
        Invocation.method(
          #toStringShort,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #toStringShort,
            [],
          ),
        ),
      ) as String);

  @override
  _i2.DiagnosticsNode toDiagnosticsNode({
    String? name,
    _i4.DiagnosticsTreeStyle? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDiagnosticsNode,
          [],
          {
            #name: name,
            #style: style,
          },
        ),
        returnValue: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
        returnValueForMissingStub: _FakeDiagnosticsNode_4(
          this,
          Invocation.method(
            #toDiagnosticsNode,
            [],
            {
              #name: name,
              #style: style,
            },
          ),
        ),
      ) as _i2.DiagnosticsNode);
}
