// Mocks generated by Mockito 5.4.4 from annotations
// in fluffychat/test/pages/new_group/new_group_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;

import 'package:fluffychat/tim/feature/automated_invite_rejection/insurer_information_repository.dart'
    as _i8;
import 'package:fluffychat/tim/feature/automated_invite_rejection/invite_rejection_policy_repository.dart'
    as _i7;
import 'package:fluffychat/tim/feature/automated_invite_rejection/invite_rejection_service.dart'
    as _i9;
import 'package:fluffychat/tim/feature/contact_approval/contact_approval_repository.dart'
    as _i4;
import 'package:fluffychat/tim/feature/fhir/search/fhir_search_service.dart'
    as _i5;
import 'package:fluffychat/tim/feature/fhir/settings/fhir_account_service.dart'
    as _i6;
import 'package:fluffychat/tim/feature/tim_version/tim_version_service.dart'
    as _i2;
import 'package:fluffychat/tim/shared/matrix/tim_matrix.dart' as _i3;
import 'package:fluffychat/tim/shared/matrix/tim_matrix_client.dart' as _i11;
import 'package:fluffychat/tim/shared/matrix/tim_matrix_crypto.dart' as _i12;
import 'package:fluffychat/tim/shared/tim_auth_state.dart' as _i10;
import 'package:fluffychat/tim/shared/tim_services.dart' as _i15;
import 'package:matrix/matrix.dart' as _i14;
import 'package:matrix/src/utils/cached_stream_controller.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTimVersionService_0 extends _i1.SmartFake
    implements _i2.TimVersionService {
  _FakeTimVersionService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimMatrix_1 extends _i1.SmartFake implements _i3.TimMatrix {
  _FakeTimMatrix_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContactApprovalRepository_2 extends _i1.SmartFake
    implements _i4.ContactApprovalRepository {
  _FakeContactApprovalRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFhirSearchService_3 extends _i1.SmartFake
    implements _i5.FhirSearchService {
  _FakeFhirSearchService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFhirAccountService_4 extends _i1.SmartFake
    implements _i6.FhirAccountService {
  _FakeFhirAccountService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInviteRejectionPolicyRepository_5 extends _i1.SmartFake
    implements _i7.InviteRejectionPolicyRepository {
  _FakeInviteRejectionPolicyRepository_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsurerInformationRepository_6 extends _i1.SmartFake
    implements _i8.InsurerInformationRepository {
  _FakeInsurerInformationRepository_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInviteRejectionService_7 extends _i1.SmartFake
    implements _i9.InviteRejectionService {
  _FakeInviteRejectionService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimAuthState_8 extends _i1.SmartFake implements _i10.TimAuthState {
  _FakeTimAuthState_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimMatrixClient_9 extends _i1.SmartFake
    implements _i11.TimMatrixClient {
  _FakeTimMatrixClient_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimMatrixCrypto_10 extends _i1.SmartFake
    implements _i12.TimMatrixCrypto {
  _FakeTimMatrixCrypto_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_11 extends _i1.SmartFake implements Uri {
  _FakeUri_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCachedStreamController_12<T> extends _i1.SmartFake
    implements _i13.CachedStreamController<T> {
  _FakeCachedStreamController_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRoomEventsResponse_13 extends _i1.SmartFake
    implements _i14.GetRoomEventsResponse {
  _FakeGetRoomEventsResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimServices extends _i1.Mock implements _i15.TimServices {
  @override
  set tokenDispenserUrl(String? _tokenDispenserUrl) => super.noSuchMethod(
        Invocation.setter(
          #tokenDispenserUrl,
          _tokenDispenserUrl,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TimVersionService get timVersionService => (super.noSuchMethod(
        Invocation.getter(#timVersionService),
        returnValue: _FakeTimVersionService_0(
          this,
          Invocation.getter(#timVersionService),
        ),
        returnValueForMissingStub: _FakeTimVersionService_0(
          this,
          Invocation.getter(#timVersionService),
        ),
      ) as _i2.TimVersionService);

  @override
  _i3.TimMatrix matrix() => (super.noSuchMethod(
        Invocation.method(
          #matrix,
          [],
        ),
        returnValue: _FakeTimMatrix_1(
          this,
          Invocation.method(
            #matrix,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeTimMatrix_1(
          this,
          Invocation.method(
            #matrix,
            [],
          ),
        ),
      ) as _i3.TimMatrix);

  @override
  _i4.ContactApprovalRepository contactsApprovalRepository() =>
      (super.noSuchMethod(
        Invocation.method(
          #contactsApprovalRepository,
          [],
        ),
        returnValue: _FakeContactApprovalRepository_2(
          this,
          Invocation.method(
            #contactsApprovalRepository,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeContactApprovalRepository_2(
          this,
          Invocation.method(
            #contactsApprovalRepository,
            [],
          ),
        ),
      ) as _i4.ContactApprovalRepository);

  @override
  _i5.FhirSearchService fhirSearchService() => (super.noSuchMethod(
        Invocation.method(
          #fhirSearchService,
          [],
        ),
        returnValue: _FakeFhirSearchService_3(
          this,
          Invocation.method(
            #fhirSearchService,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFhirSearchService_3(
          this,
          Invocation.method(
            #fhirSearchService,
            [],
          ),
        ),
      ) as _i5.FhirSearchService);

  @override
  _i6.FhirAccountService fhirAccountService() => (super.noSuchMethod(
        Invocation.method(
          #fhirAccountService,
          [],
        ),
        returnValue: _FakeFhirAccountService_4(
          this,
          Invocation.method(
            #fhirAccountService,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFhirAccountService_4(
          this,
          Invocation.method(
            #fhirAccountService,
            [],
          ),
        ),
      ) as _i6.FhirAccountService);

  @override
  _i7.InviteRejectionPolicyRepository inviteRejectionPolicyRepository() =>
      (super.noSuchMethod(
        Invocation.method(
          #inviteRejectionPolicyRepository,
          [],
        ),
        returnValue: _FakeInviteRejectionPolicyRepository_5(
          this,
          Invocation.method(
            #inviteRejectionPolicyRepository,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeInviteRejectionPolicyRepository_5(
          this,
          Invocation.method(
            #inviteRejectionPolicyRepository,
            [],
          ),
        ),
      ) as _i7.InviteRejectionPolicyRepository);

  @override
  _i8.InsurerInformationRepository insurerInformationRepository() =>
      (super.noSuchMethod(
        Invocation.method(
          #insurerInformationRepository,
          [],
        ),
        returnValue: _FakeInsurerInformationRepository_6(
          this,
          Invocation.method(
            #insurerInformationRepository,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeInsurerInformationRepository_6(
          this,
          Invocation.method(
            #insurerInformationRepository,
            [],
          ),
        ),
      ) as _i8.InsurerInformationRepository);

  @override
  _i9.InviteRejectionService inviteRejectionService() => (super.noSuchMethod(
        Invocation.method(
          #inviteRejectionService,
          [],
        ),
        returnValue: _FakeInviteRejectionService_7(
          this,
          Invocation.method(
            #inviteRejectionService,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeInviteRejectionService_7(
          this,
          Invocation.method(
            #inviteRejectionService,
            [],
          ),
        ),
      ) as _i9.InviteRejectionService);

  @override
  _i10.TimAuthState timAuthState() => (super.noSuchMethod(
        Invocation.method(
          #timAuthState,
          [],
        ),
        returnValue: _FakeTimAuthState_8(
          this,
          Invocation.method(
            #timAuthState,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeTimAuthState_8(
          this,
          Invocation.method(
            #timAuthState,
            [],
          ),
        ),
      ) as _i10.TimAuthState);
}

/// A class which mocks [TimMatrix].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimMatrix extends _i1.Mock implements _i3.TimMatrix {
  @override
  _i11.TimMatrixClient client() => (super.noSuchMethod(
        Invocation.method(
          #client,
          [],
        ),
        returnValue: _FakeTimMatrixClient_9(
          this,
          Invocation.method(
            #client,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeTimMatrixClient_9(
          this,
          Invocation.method(
            #client,
            [],
          ),
        ),
      ) as _i11.TimMatrixClient);

  @override
  _i12.TimMatrixCrypto crypto() => (super.noSuchMethod(
        Invocation.method(
          #crypto,
          [],
        ),
        returnValue: _FakeTimMatrixCrypto_10(
          this,
          Invocation.method(
            #crypto,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeTimMatrixCrypto_10(
          this,
          Invocation.method(
            #crypto,
            [],
          ),
        ),
      ) as _i12.TimMatrixCrypto);
}

/// A class which mocks [TimMatrixClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimMatrixClient extends _i1.Mock implements _i11.TimMatrixClient {
  @override
  String get userID => (super.noSuchMethod(
        Invocation.getter(#userID),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#userID),
        ),
        returnValueForMissingStub: _i16.dummyValue<String>(
          this,
          Invocation.getter(#userID),
        ),
      ) as String);

  @override
  String get accessToken => (super.noSuchMethod(
        Invocation.getter(#accessToken),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
        returnValueForMissingStub: _i16.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
      ) as String);

  @override
  Uri get homeserver => (super.noSuchMethod(
        Invocation.getter(#homeserver),
        returnValue: _FakeUri_11(
          this,
          Invocation.getter(#homeserver),
        ),
        returnValueForMissingStub: _FakeUri_11(
          this,
          Invocation.getter(#homeserver),
        ),
      ) as Uri);

  @override
  _i13.CachedStreamController<_i14.EventUpdate> get onEventUpdate =>
      (super.noSuchMethod(
        Invocation.getter(#onEventUpdate),
        returnValue: _FakeCachedStreamController_12<_i14.EventUpdate>(
          this,
          Invocation.getter(#onEventUpdate),
        ),
        returnValueForMissingStub:
            _FakeCachedStreamController_12<_i14.EventUpdate>(
          this,
          Invocation.getter(#onEventUpdate),
        ),
      ) as _i13.CachedStreamController<_i14.EventUpdate>);

  @override
  _i17.Future<String?> getDisplayName(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayName,
          [userId],
        ),
        returnValue: _i17.Future<String?>.value(),
        returnValueForMissingStub: _i17.Future<String?>.value(),
      ) as _i17.Future<String?>);

  @override
  _i14.Room? getRoomById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRoomById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i14.Room?);

  @override
  _i17.Future<_i14.GetRoomEventsResponse> getRoomEvents(
    String? roomId,
    _i14.Direction? dir, {
    String? from,
    String? to,
    int? limit,
    String? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoomEvents,
          [
            roomId,
            dir,
          ],
          {
            #from: from,
            #to: to,
            #limit: limit,
            #filter: filter,
          },
        ),
        returnValue: _i17.Future<_i14.GetRoomEventsResponse>.value(
            _FakeGetRoomEventsResponse_13(
          this,
          Invocation.method(
            #getRoomEvents,
            [
              roomId,
              dir,
            ],
            {
              #from: from,
              #to: to,
              #limit: limit,
              #filter: filter,
            },
          ),
        )),
        returnValueForMissingStub:
            _i17.Future<_i14.GetRoomEventsResponse>.value(
                _FakeGetRoomEventsResponse_13(
          this,
          Invocation.method(
            #getRoomEvents,
            [
              roomId,
              dir,
            ],
            {
              #from: from,
              #to: to,
              #limit: limit,
              #filter: filter,
            },
          ),
        )),
      ) as _i17.Future<_i14.GetRoomEventsResponse>);

  @override
  _i17.Future<String> startDirectChatWithCustomRoomType(
    String? mxid, {
    bool? isCaseReference = false,
    Map<String, dynamic>? creationContent,
    List<_i14.Invite3pid>? invite3pid,
    String? name,
    String? roomAliasName,
    String? roomVersion,
    String? topic,
    _i14.Visibility? visibility,
    bool? enableEncryption,
    List<_i14.StateEvent>? initialState,
    bool? waitForSync = true,
    Map<String, dynamic>? powerLevelContentOverride,
    _i14.CreateRoomPreset? preset = _i14.CreateRoomPreset.trustedPrivateChat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startDirectChatWithCustomRoomType,
          [mxid],
          {
            #isCaseReference: isCaseReference,
            #creationContent: creationContent,
            #invite3pid: invite3pid,
            #name: name,
            #roomAliasName: roomAliasName,
            #roomVersion: roomVersion,
            #topic: topic,
            #visibility: visibility,
            #enableEncryption: enableEncryption,
            #initialState: initialState,
            #waitForSync: waitForSync,
            #powerLevelContentOverride: powerLevelContentOverride,
            #preset: preset,
          },
        ),
        returnValue: _i17.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #startDirectChatWithCustomRoomType,
            [mxid],
            {
              #isCaseReference: isCaseReference,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #name: name,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
              #visibility: visibility,
              #enableEncryption: enableEncryption,
              #initialState: initialState,
              #waitForSync: waitForSync,
              #powerLevelContentOverride: powerLevelContentOverride,
              #preset: preset,
            },
          ),
        )),
        returnValueForMissingStub:
            _i17.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #startDirectChatWithCustomRoomType,
            [mxid],
            {
              #isCaseReference: isCaseReference,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #name: name,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
              #visibility: visibility,
              #enableEncryption: enableEncryption,
              #initialState: initialState,
              #waitForSync: waitForSync,
              #powerLevelContentOverride: powerLevelContentOverride,
              #preset: preset,
            },
          ),
        )),
      ) as _i17.Future<String>);

  @override
  _i17.Future<String> createGroupChatWithCustomRoomType({
    bool? isCaseReference = false,
    String? name,
    bool? enableEncryption,
    List<String>? invite,
    _i14.CreateRoomPreset? preset = _i14.CreateRoomPreset.privateChat,
    List<_i14.StateEvent>? initialState,
    _i14.Visibility? visibility,
    bool? waitForSync = true,
    bool? groupCall = false,
    Map<String, dynamic>? powerLevelContentOverride,
    Map<String, dynamic>? creationContent,
    List<_i14.Invite3pid>? invite3pid,
    bool? isDirect = false,
    String? roomAliasName,
    String? roomVersion,
    String? topic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroupChatWithCustomRoomType,
          [],
          {
            #isCaseReference: isCaseReference,
            #name: name,
            #enableEncryption: enableEncryption,
            #invite: invite,
            #preset: preset,
            #initialState: initialState,
            #visibility: visibility,
            #waitForSync: waitForSync,
            #groupCall: groupCall,
            #powerLevelContentOverride: powerLevelContentOverride,
            #creationContent: creationContent,
            #invite3pid: invite3pid,
            #isDirect: isDirect,
            #roomAliasName: roomAliasName,
            #roomVersion: roomVersion,
            #topic: topic,
          },
        ),
        returnValue: _i17.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #createGroupChatWithCustomRoomType,
            [],
            {
              #isCaseReference: isCaseReference,
              #name: name,
              #enableEncryption: enableEncryption,
              #invite: invite,
              #preset: preset,
              #initialState: initialState,
              #visibility: visibility,
              #waitForSync: waitForSync,
              #groupCall: groupCall,
              #powerLevelContentOverride: powerLevelContentOverride,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #isDirect: isDirect,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
            },
          ),
        )),
        returnValueForMissingStub:
            _i17.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #createGroupChatWithCustomRoomType,
            [],
            {
              #isCaseReference: isCaseReference,
              #name: name,
              #enableEncryption: enableEncryption,
              #invite: invite,
              #preset: preset,
              #initialState: initialState,
              #visibility: visibility,
              #waitForSync: waitForSync,
              #groupCall: groupCall,
              #powerLevelContentOverride: powerLevelContentOverride,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #isDirect: isDirect,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
            },
          ),
        )),
      ) as _i17.Future<String>);

  @override
  _i13.CachedStreamController<_i14.BasicEvent> onAccountDataChange() =>
      (super.noSuchMethod(
        Invocation.method(
          #onAccountDataChange,
          [],
        ),
        returnValue: _FakeCachedStreamController_12<_i14.BasicEvent>(
          this,
          Invocation.method(
            #onAccountDataChange,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeCachedStreamController_12<_i14.BasicEvent>(
          this,
          Invocation.method(
            #onAccountDataChange,
            [],
          ),
        ),
      ) as _i13.CachedStreamController<_i14.BasicEvent>);

  @override
  _i17.Future<void> setAccountData(
    String? userId,
    String? type,
    Map<String, dynamic>? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAccountData,
          [
            userId,
            type,
            content,
          ],
        ),
        returnValue: _i17.Future<void>.value(),
        returnValueForMissingStub: _i17.Future<void>.value(),
      ) as _i17.Future<void>);

  @override
  _i17.Future<Map<String, dynamic>> getAccountData(
    String? userId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountData,
          [
            userId,
            type,
          ],
        ),
        returnValue:
            _i17.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i17.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i17.Future<Map<String, dynamic>>);

  @override
  void leaveRoom(
    String? roomId, {
    String? reason,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #leaveRoom,
          [roomId],
          {#reason: reason},
        ),
        returnValueForMissingStub: null,
      );
}
