name: fluffychat
description: Chat with your friends.
publish_to: none
version: 1.18.0+3360

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_inappwebview: ^5.7.2+3
  flutter_web_auth_2: ^2.1.1
  adaptive_dialog: ^1.9.0-no-macos.2
  animations: ^2.0.7
  archive: ^3.3.0
  badges: ^2.0.3
  blurhash_dart: ^1.1.0
  callkeep: ^0.3.2
  chewie: ^1.3.6
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cupertino_icons: any
  dart_jsonwebtoken: ^2.7.1
  desktop_drop: ^0.4.0
  desktop_lifecycle: ^0.1.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^8.0.0
  dynamic_color: ^1.6.0
  emoji_picker_flutter: ^1.5.1
  emoji_proposal: ^0.0.1
  emojis: ^0.9.9
  equatable: ^2.0.5
  file_picker: ^5.2.6
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_app_lock: ^3.0.0
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_foreground_task: ^3.10.0
  flutter_highlighter: ^0.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^12.0.2
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.1
  flutter_map: ^3.1.0
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0
  flutter_ringtone_player: ^3.1.1
  flutter_secure_storage: ^7.0.1
  flutter_typeahead: ^4.3.2
  flutter_webrtc: ^0.9.32
  future_loading_dialog: ^0.2.3
  geolocator: ^7.6.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+8
  intl: any
  json_annotation: ^4.8.0
  just_audio: ^0.9.30
  just_audio_mpv: ^0.1.6
  keyboard_shortcuts: ^0.1.4
  linkify: ^5.0.0
  latlong2: ^0.8.1
  matrix: 0.18.0
  native_imaging: ^0.1.0
  package_info_plus: ^4.0.0
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: 4.0.0
  receive_sharing_intent: ^1.4.5
  record: ^4.4.4
  retry: ^3.1.0
  rxdart: ^0.27.7
  scroll_to_index: ^3.0.1
  share_plus: ^7.0.0
  shared_preferences: 2.0.15 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  swipe_to_action: ^0.2.0
  tor_detector_web: ^1.1.0
  tuple: ^2.0.1
  uni_links: ^0.5.1
  unifiedpush: ^4.0.3
  universal_html: ^2.0.8
  url_launcher: ^6.0.20
  vibration: ^1.7.4-nullsafety.0
  video_compress: ^3.1.1
  video_player: ^2.2.18
  vrouter: ^1.2.0+21
  wakelock: ^0.6.2
  webrtc_interface: ^1.0.10


dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  json_serializable: 6.6.1
  mockito: ^5.4.0
  path_provider_platform_interface: ^2.0.5
  plugin_platform_interface: ^2.1.3
  share_plus_platform_interface: ^3.2.0
  translations_cleaner: ^0.0.5

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/akquinet-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/
    - fonts/MaterialIcons-LICENSE.txt
    - fonts/NotoEmoji/LICENSE.txt
    - fonts/Roboto/LICENSE.txt
    - packages/cupertino_icons/assets/LICENSE.txt
    - packages/flutter_inappwebview/assets/LICENSE.txt
    - packages/flutter_math_fork/lib/katex_fonts/LICENSE.txt
    - packages/wakelock_web/assets/LICENSE.txt
    - README.md

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto/RobotoMono-Regular.ttf
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

dependency_overrides:
  # Until all dependencies are compatible. Missing: flutter_matrix_html
  ffi: ^2.0.0
  # fake secure storage plugin for Windows
  # See: https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/15161
  flutter_secure_storage_windows:
    git:
      url: https://gitlab.com/TheOneWithTheBraid/flutter_secure_storage_windows.git
      ref: main
  geolocator_android:
    hosted:
      name: geolocator_android
      url: https://hanntech-gmbh.gitlab.io/free2pass/flutter-geolocator-floss
  # waiting for null safety
  # Upstream pull request: https://github.com/AntoineMarcel/keyboard_shortcuts/pull/13
  keyboard_shortcuts:
    git:
      url: https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git
      ref: null-safety
  # blocked upgrade of package_info_plus for null safety
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203
  wakelock_windows:
    git:
      url: https://github.com/chandrabezzo/wakelock.git
      ref: main
      path: wakelock_windows/
