// Mocks generated by Mockito 5.4.4 from annotations
// in fluffychat/test/tim/feature/automated_invite_rejection/invite_rejection_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:fluffychat/tim/feature/automated_invite_rejection/insurer_information_repository.dart'
    as _i12;
import 'package:fluffychat/tim/feature/automated_invite_rejection/invite_rejection_policy.dart'
    as _i9;
import 'package:fluffychat/tim/feature/automated_invite_rejection/invite_rejection_policy_repository.dart'
    as _i8;
import 'package:fluffychat/tim/feature/tim_version/tim_version.dart' as _i7;
import 'package:fluffychat/tim/feature/tim_version/tim_version_repository.dart'
    as _i2;
import 'package:fluffychat/tim/feature/tim_version/tim_version_service.dart'
    as _i5;
import 'package:fluffychat/tim/shared/matrix/tim_matrix_client.dart' as _i11;
import 'package:fpdart/fpdart.dart' as _i13;
import 'package:matrix/matrix.dart' as _i4;
import 'package:matrix/src/utils/cached_stream_controller.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:tim_information_api/api.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTimVersionRepository_0 extends _i1.SmartFake
    implements _i2.TimVersionRepository {
  _FakeTimVersionRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCachedStreamController_2<T> extends _i1.SmartFake
    implements _i3.CachedStreamController<T> {
  _FakeCachedStreamController_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetRoomEventsResponse_3 extends _i1.SmartFake
    implements _i4.GetRoomEventsResponse {
  _FakeGetRoomEventsResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimVersionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimVersionService extends _i1.Mock implements _i5.TimVersionService {
  @override
  _i2.TimVersionRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTimVersionRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTimVersionRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TimVersionRepository);

  @override
  _i6.Future<void> set(_i7.TimVersion? version) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [version],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.TimVersion> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i6.Future<_i7.TimVersion>.value(_i7.TimVersion.classic),
        returnValueForMissingStub:
            _i6.Future<_i7.TimVersion>.value(_i7.TimVersion.classic),
      ) as _i6.Future<_i7.TimVersion>);

  @override
  _i6.Future<bool> versionFeaturesClientSideInviteRejection() =>
      (super.noSuchMethod(
        Invocation.method(
          #versionFeaturesClientSideInviteRejection,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [InviteRejectionPolicyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInviteRejectionPolicyRepository extends _i1.Mock
    implements _i8.InviteRejectionPolicyRepository {
  @override
  void listenToNewRejectionPolicy() => super.noSuchMethod(
        Invocation.method(
          #listenToNewRejectionPolicy,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setNewPolicy(_i9.InviteRejectionPolicy? newPolicy) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNewPolicy,
          [newPolicy],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i9.InviteRejectionPolicy> getCurrentPolicy() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPolicy,
          [],
        ),
        returnValue: _i6.Future<_i9.InviteRejectionPolicy>.value(
            _i10.dummyValue<_i9.InviteRejectionPolicy>(
          this,
          Invocation.method(
            #getCurrentPolicy,
            [],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i9.InviteRejectionPolicy>.value(
            _i10.dummyValue<_i9.InviteRejectionPolicy>(
          this,
          Invocation.method(
            #getCurrentPolicy,
            [],
          ),
        )),
      ) as _i6.Future<_i9.InviteRejectionPolicy>);
}

/// A class which mocks [TimMatrixClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimMatrixClient extends _i1.Mock implements _i11.TimMatrixClient {
  @override
  String get userID => (super.noSuchMethod(
        Invocation.getter(#userID),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#userID),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#userID),
        ),
      ) as String);

  @override
  String get accessToken => (super.noSuchMethod(
        Invocation.getter(#accessToken),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
      ) as String);

  @override
  Uri get homeserver => (super.noSuchMethod(
        Invocation.getter(#homeserver),
        returnValue: _FakeUri_1(
          this,
          Invocation.getter(#homeserver),
        ),
        returnValueForMissingStub: _FakeUri_1(
          this,
          Invocation.getter(#homeserver),
        ),
      ) as Uri);

  @override
  _i3.CachedStreamController<_i4.EventUpdate> get onEventUpdate =>
      (super.noSuchMethod(
        Invocation.getter(#onEventUpdate),
        returnValue: _FakeCachedStreamController_2<_i4.EventUpdate>(
          this,
          Invocation.getter(#onEventUpdate),
        ),
        returnValueForMissingStub:
            _FakeCachedStreamController_2<_i4.EventUpdate>(
          this,
          Invocation.getter(#onEventUpdate),
        ),
      ) as _i3.CachedStreamController<_i4.EventUpdate>);

  @override
  _i6.Future<String?> getDisplayName(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayName,
          [userId],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i4.Room? getRoomById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRoomById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i4.Room?);

  @override
  _i6.Future<_i4.GetRoomEventsResponse> getRoomEvents(
    String? roomId,
    _i4.Direction? dir, {
    String? from,
    String? to,
    int? limit,
    String? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoomEvents,
          [
            roomId,
            dir,
          ],
          {
            #from: from,
            #to: to,
            #limit: limit,
            #filter: filter,
          },
        ),
        returnValue: _i6.Future<_i4.GetRoomEventsResponse>.value(
            _FakeGetRoomEventsResponse_3(
          this,
          Invocation.method(
            #getRoomEvents,
            [
              roomId,
              dir,
            ],
            {
              #from: from,
              #to: to,
              #limit: limit,
              #filter: filter,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.GetRoomEventsResponse>.value(
            _FakeGetRoomEventsResponse_3(
          this,
          Invocation.method(
            #getRoomEvents,
            [
              roomId,
              dir,
            ],
            {
              #from: from,
              #to: to,
              #limit: limit,
              #filter: filter,
            },
          ),
        )),
      ) as _i6.Future<_i4.GetRoomEventsResponse>);

  @override
  _i6.Future<String> startDirectChat(
    String? mxid, {
    bool? enableEncryption,
    List<_i4.StateEvent>? initialState,
    bool? waitForSync = true,
    Map<String, dynamic>? powerLevelContentOverride,
    _i4.CreateRoomPreset? preset = _i4.CreateRoomPreset.trustedPrivateChat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startDirectChat,
          [mxid],
          {
            #enableEncryption: enableEncryption,
            #initialState: initialState,
            #waitForSync: waitForSync,
            #powerLevelContentOverride: powerLevelContentOverride,
            #preset: preset,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #startDirectChat,
            [mxid],
            {
              #enableEncryption: enableEncryption,
              #initialState: initialState,
              #waitForSync: waitForSync,
              #powerLevelContentOverride: powerLevelContentOverride,
              #preset: preset,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #startDirectChat,
            [mxid],
            {
              #enableEncryption: enableEncryption,
              #initialState: initialState,
              #waitForSync: waitForSync,
              #powerLevelContentOverride: powerLevelContentOverride,
              #preset: preset,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> startDirectChatWithCustomRoomType(
    String? mxid, {
    bool? isCaseReference = false,
    Map<String, dynamic>? creationContent,
    List<_i4.Invite3pid>? invite3pid,
    String? name,
    String? roomAliasName,
    String? roomVersion,
    String? topic,
    _i4.Visibility? visibility,
    bool? enableEncryption,
    List<_i4.StateEvent>? initialState,
    bool? waitForSync = true,
    Map<String, dynamic>? powerLevelContentOverride,
    _i4.CreateRoomPreset? preset = _i4.CreateRoomPreset.trustedPrivateChat,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startDirectChatWithCustomRoomType,
          [mxid],
          {
            #isCaseReference: isCaseReference,
            #creationContent: creationContent,
            #invite3pid: invite3pid,
            #name: name,
            #roomAliasName: roomAliasName,
            #roomVersion: roomVersion,
            #topic: topic,
            #visibility: visibility,
            #enableEncryption: enableEncryption,
            #initialState: initialState,
            #waitForSync: waitForSync,
            #powerLevelContentOverride: powerLevelContentOverride,
            #preset: preset,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #startDirectChatWithCustomRoomType,
            [mxid],
            {
              #isCaseReference: isCaseReference,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #name: name,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
              #visibility: visibility,
              #enableEncryption: enableEncryption,
              #initialState: initialState,
              #waitForSync: waitForSync,
              #powerLevelContentOverride: powerLevelContentOverride,
              #preset: preset,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #startDirectChatWithCustomRoomType,
            [mxid],
            {
              #isCaseReference: isCaseReference,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #name: name,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
              #visibility: visibility,
              #enableEncryption: enableEncryption,
              #initialState: initialState,
              #waitForSync: waitForSync,
              #powerLevelContentOverride: powerLevelContentOverride,
              #preset: preset,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> createGroupChatWithCustomRoomType({
    bool? isCaseReference = false,
    String? name,
    bool? enableEncryption,
    List<String>? invite,
    _i4.CreateRoomPreset? preset = _i4.CreateRoomPreset.privateChat,
    List<_i4.StateEvent>? initialState,
    _i4.Visibility? visibility,
    bool? waitForSync = true,
    bool? groupCall = false,
    Map<String, dynamic>? powerLevelContentOverride,
    Map<String, dynamic>? creationContent,
    List<_i4.Invite3pid>? invite3pid,
    bool? isDirect = false,
    String? roomAliasName,
    String? roomVersion,
    String? topic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroupChatWithCustomRoomType,
          [],
          {
            #isCaseReference: isCaseReference,
            #name: name,
            #enableEncryption: enableEncryption,
            #invite: invite,
            #preset: preset,
            #initialState: initialState,
            #visibility: visibility,
            #waitForSync: waitForSync,
            #groupCall: groupCall,
            #powerLevelContentOverride: powerLevelContentOverride,
            #creationContent: creationContent,
            #invite3pid: invite3pid,
            #isDirect: isDirect,
            #roomAliasName: roomAliasName,
            #roomVersion: roomVersion,
            #topic: topic,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #createGroupChatWithCustomRoomType,
            [],
            {
              #isCaseReference: isCaseReference,
              #name: name,
              #enableEncryption: enableEncryption,
              #invite: invite,
              #preset: preset,
              #initialState: initialState,
              #visibility: visibility,
              #waitForSync: waitForSync,
              #groupCall: groupCall,
              #powerLevelContentOverride: powerLevelContentOverride,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #isDirect: isDirect,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #createGroupChatWithCustomRoomType,
            [],
            {
              #isCaseReference: isCaseReference,
              #name: name,
              #enableEncryption: enableEncryption,
              #invite: invite,
              #preset: preset,
              #initialState: initialState,
              #visibility: visibility,
              #waitForSync: waitForSync,
              #groupCall: groupCall,
              #powerLevelContentOverride: powerLevelContentOverride,
              #creationContent: creationContent,
              #invite3pid: invite3pid,
              #isDirect: isDirect,
              #roomAliasName: roomAliasName,
              #roomVersion: roomVersion,
              #topic: topic,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i3.CachedStreamController<_i4.BasicEvent> onAccountDataChange() =>
      (super.noSuchMethod(
        Invocation.method(
          #onAccountDataChange,
          [],
        ),
        returnValue: _FakeCachedStreamController_2<_i4.BasicEvent>(
          this,
          Invocation.method(
            #onAccountDataChange,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeCachedStreamController_2<_i4.BasicEvent>(
          this,
          Invocation.method(
            #onAccountDataChange,
            [],
          ),
        ),
      ) as _i3.CachedStreamController<_i4.BasicEvent>);

  @override
  _i6.Future<void> setAccountData(
    String? userId,
    String? type,
    Map<String, dynamic>? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAccountData,
          [
            userId,
            type,
            content,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getAccountData(
    String? userId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountData,
          [
            userId,
            type,
          ],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  void leaveRoom(
    String? roomId, {
    String? reason,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #leaveRoom,
          [roomId],
          {#reason: reason},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [InsurerInformationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsurerInformationRepository extends _i1.Mock
    implements _i12.InsurerInformationRepository {
  @override
  _i6.Future<
      _i13.Either<
          _i14.ApiException,
          _i14
          .V1ServerFindByIkGet200Response?>> getServerByIk(String? ikNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerByIk,
          [ikNumber],
        ),
        returnValue: _i6.Future<
            _i13.Either<_i14.ApiException,
                _i14.V1ServerFindByIkGet200Response?>>.value(_i10.dummyValue<
            _i13
            .Either<_i14.ApiException, _i14.V1ServerFindByIkGet200Response?>>(
          this,
          Invocation.method(
            #getServerByIk,
            [ikNumber],
          ),
        )),
        returnValueForMissingStub: _i6.Future<
            _i13.Either<_i14.ApiException,
                _i14.V1ServerFindByIkGet200Response?>>.value(_i10.dummyValue<
            _i13
            .Either<_i14.ApiException, _i14.V1ServerFindByIkGet200Response?>>(
          this,
          Invocation.method(
            #getServerByIk,
            [ikNumber],
          ),
        )),
      ) as _i6.Future<
          _i13
          .Either<_i14.ApiException, _i14.V1ServerFindByIkGet200Response?>>);

  @override
  _i6.Future<_i13.Option<bool?>> doesServerBelongToInsurer(
          String? serverName) =>
      (super.noSuchMethod(
        Invocation.method(
          #doesServerBelongToInsurer,
          [serverName],
        ),
        returnValue: _i6.Future<_i13.Option<bool?>>.value(
            _i10.dummyValue<_i13.Option<bool?>>(
          this,
          Invocation.method(
            #doesServerBelongToInsurer,
            [serverName],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i13.Option<bool?>>.value(
            _i10.dummyValue<_i13.Option<bool?>>(
          this,
          Invocation.method(
            #doesServerBelongToInsurer,
            [serverName],
          ),
        )),
      ) as _i6.Future<_i13.Option<bool?>>);

  @override
  void initApiClientIfNeeded() => super.noSuchMethod(
        Invocation.method(
          #initApiClientIfNeeded,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
