// Mocks generated by Mockito 5.4.4 from annotations
// in fluffychat/test/utils/data_preperation_helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:matrix/matrix_api_lite/generated/model.dart' as _i2;
import 'package:matrix/matrix_api_lite/model/matrix_event.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetRelatingEventsResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRelatingEventsResponse extends _i1.Mock
    implements _i2.GetRelatingEventsResponse {
  @override
  List<_i3.MatrixEvent> get chunk => (super.noSuchMethod(
        Invocation.getter(#chunk),
        returnValue: <_i3.MatrixEvent>[],
        returnValueForMissingStub: <_i3.MatrixEvent>[],
      ) as List<_i3.MatrixEvent>);

  @override
  set chunk(List<_i3.MatrixEvent>? _chunk) => super.noSuchMethod(
        Invocation.setter(
          #chunk,
          _chunk,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set nextBatch(String? _nextBatch) => super.noSuchMethod(
        Invocation.setter(
          #nextBatch,
          _nextBatch,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set prevBatch(String? _prevBatch) => super.noSuchMethod(
        Invocation.setter(
          #prevBatch,
          _prevBatch,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set recursionDepth(int? _recursionDepth) => super.noSuchMethod(
        Invocation.setter(
          #recursionDepth,
          _recursionDepth,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, Object?> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);
}
