ingress:
  enabled: true
  className: "nginx-internal"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: olafs-tim-client.eu.timref.akquinet.nx2.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-timessengerclient-general
      hosts:
        - olafs-tim-client.eu.timref.akquinet.nx2.dev