// Mocks generated by Mockito 5.4.2 from annotations
// in fluffychat/test/tim/shared/tim_auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fluffychat/tim/feature/fhir/fhir_config.dart' as _i3;
import 'package:fluffychat/tim/feature/hba/authentication/hba_authentication.dart'
    as _i4;
import 'package:fluffychat/tim/shared/tim_auth_token.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTimAuthToken_0 extends _i1.SmartFake implements _i2.TimAuthToken {
  _FakeTimAuthToken_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FhirConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockFhirConfig extends _i1.Mock implements _i3.FhirConfig {
  MockFhirConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: '',
      ) as String);
  @override
  String get searchBase => (super.noSuchMethod(
        Invocation.getter(#searchBase),
        returnValue: '',
      ) as String);
  @override
  String get authBase => (super.noSuchMethod(
        Invocation.getter(#authBase),
        returnValue: '',
      ) as String);
  @override
  String get ownerBase => (super.noSuchMethod(
        Invocation.getter(#ownerBase),
        returnValue: '',
      ) as String);
  @override
  String fhirServer() => (super.noSuchMethod(
        Invocation.method(
          #fhirServer,
          [],
        ),
        returnValue: '',
      ) as String);
}

/// A class which mocks [HbaAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockHbaAuthentication extends _i1.Mock implements _i4.HbaAuthentication {
  MockHbaAuthentication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.TimAuthToken> getHbaToken() => (super.noSuchMethod(
        Invocation.method(
          #getHbaToken,
          [],
        ),
        returnValue: _i5.Future<_i2.TimAuthToken>.value(_FakeTimAuthToken_0(
          this,
          Invocation.method(
            #getHbaToken,
            [],
          ),
        )),
      ) as _i5.Future<_i2.TimAuthToken>);
  @override
  _i5.Future<_i2.TimAuthToken> getHbaTokenFromUrl(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHbaTokenFromUrl,
          [url],
        ),
        returnValue: _i5.Future<_i2.TimAuthToken>.value(_FakeTimAuthToken_0(
          this,
          Invocation.method(
            #getHbaTokenFromUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i2.TimAuthToken>);
}
